---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=imager.conf.j2 dest=/etc/init/portfolio.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=portfolio state=restarted
